// layout.tsx 
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="layout-container">
          {/* 상단 메뉴 */}
          <header className="top-menu">
            <div className="top-menu-content">
              <h1 className="logo">My App</h1>
              <nav className="top-nav">
                <Link href="/" className="nav-link">홈</Link>
                <Link href="/users" className="nav-link">사용자</Link>
                <Link href="/api/todo" className="nav-link">API</Link>
              </nav>
            </div>
          </header>

          <div className="main-wrapper">
            {/* 왼쪽 사이드바 메뉴 */}
            <aside className="sidebar">
              <nav className="sidebar-nav">
                <Link href="/" className="sidebar-link">
                  <span></span> Todo 목록
                </Link>
                <Link href="/users" className="sidebar-link">
                  <span></span> 사용자 관리
                </Link>
              </nav>
            </aside>

            {/* 메인 컨텐츠 영역 */}
            <main className="main-content">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}

